have_fun: true
code_review:
  disable: false
  comment_severity_threshold: MEDIUM
  max_review_comments: 5
  pull_request_opened:
    help: false
    summary: false
    code_review: true
  pull_request_updated:
    help: false
    summary: false
    code_review: true