"""hotel

Revision ID: 068b6efb8901
Revises: 
Create Date: 2024-09-23 15:00:35.833271

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '068b6efb8901'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest',
    sa.Column('guestno', sa.Numeric(precision=5), nullable=False),
    sa.Column('guestname', sa.String(length=20), nullable=True),
    sa.Column('guestaddress', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('guestno')
    )
    op.create_index(op.f('ix_guest_guestno'), 'guest', ['guestno'], unique=False)
    op.create_table('hotel',
    sa.Column('hotelno', sa.String(length=10), nullable=False),
    sa.Column('hotelname', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('hotelno')
    )
    op.create_index(op.f('ix_hotel_hotelno'), 'hotel', ['hotelno'], unique=False)
    op.create_table('room',
    sa.Column('roomno', sa.Numeric(precision=5), nullable=False),
    sa.Column('hotelno', sa.String(length=10), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['hotelno'], ['hotel.hotelno'], ),
    sa.PrimaryKeyConstraint('roomno', 'hotelno')
    )
    op.create_table('booking',
    sa.Column('hotelno', sa.String(length=10), nullable=False),
    sa.Column('guestno', sa.Numeric(precision=5), nullable=False),
    sa.Column('datefrom', sa.DateTime(), nullable=False),
    sa.Column('dateto', sa.DateTime(), nullable=True),
    sa.Column('roomno', sa.Numeric(precision=5), nullable=False),
    sa.ForeignKeyConstraint(['guestno'], ['guest.guestno'], ),
    sa.ForeignKeyConstraint(['hotelno'], ['hotel.hotelno'], ),
    sa.ForeignKeyConstraint(['roomno'], ['room.roomno'], ),
    sa.PrimaryKeyConstraint('hotelno', 'guestno', 'datefrom', 'roomno')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    op.drop_table('room')
    op.drop_index(op.f('ix_hotel_hotelno'), table_name='hotel')
    op.drop_table('hotel')
    op.drop_index(op.f('ix_guest_guestno'), table_name='guest')
    op.drop_table('guest')
    # ### end Alembic commands ###
